pull_request_rules:
  - name: Automatic merge on CI success and review
    conditions:
      - "#approved-reviews-by>=1"
      - label!=do-not-merge
      - label!=WIP
    request_reviews:
      teams:
        - "@servicemesher/istio-handbook-wg-maintainers"
    actions:
      merge:
        method: squash
        strict: true
